- README.md
Review it, change headers or images (or image sources) if you want.
> Issue #40 got "fixed"

- internal/ui/privatechats.go
- internal/ui/window.go
The private list has been completely refactor, it now supports:
* Updates via events
* Filtering friends by user channels, to avoid confusion due to duplication
* Channelmarkers for unread messages and for current channel
> Privatelist refactoring

- README.md
> Update README with Homebrew instructions

- app/app.go
- readstate/readmarkers.go
- ui/channeltree.go
- ui/privatechats.go
- ui/window.go
Initial version for resolving #12 
Clients running this version will initially have all channels marked as read.
This implementation still has the problem that channels that shouldn't be seen can be seen and are taken into consideration when checking for unread messages.
> Readmarkers

- ui/channeltree.go
Resolves #84 (and partially resolves #1).
> Now checking if the user has permissions to read channel messages.

- ui/editor.go
- ui/window.go
Fixes #96
-Previous, typing @ at any point would bring up the `mention handler`.
Now it is only shown if it is the first character in the text box, or if
it is prefixed by a space.
-Minor code cleanup.
> Fixed mention handler bug.

- ui/editor.go
- ui/window.go
> Mention fix

- ui/window.go
> Failing to send long messages no longer erases your message.

- shortcuts/shortcuts.go
- ui/window.go
Pressing alt+L switches to the previous channel/buffer.
Resolves #98
> Switch to previous channel/buffer with shortcut

- times/times.go
- ui/chatview.go
- ui/window.go
> All quotes now use UTC time.

- .github/ISSUE_TEMPLATE/Bug_report.md
- README.md
- shortcuts/shortcuts.go
- ui/window.go
- util/fuzzy/fuzzy.go
- util/fuzzy/fuzzy_test.go
Resolves #122 
Uses a naive version of fuzzy finding to order search results.
> Mention result ordering

- discordutil/message.go
- readstate/readmarkers.go
- ui/editor.go
- ui/window.go
- util/fuzzy/fuzzy.go
- util/fuzzy/fuzzy_test.go
Manually merged version of #134
Resolves #122
> Mention results merged

- times/times.go
- ui/chatview.go
> ChatView Day delimiters between chats

- ui/login.go
before, you could only use tab to switch between input fields, made it so you can use arrow keys
> enable arrow key navigation of login input fields

- commands/commandimpls/account.go
- commands/commandimpls/friends.go
- commands/commandimpls/manual.go
- commands/commandimpls/user.go
- config/config.go
- ui/login.go
I don't really care about grammar, but these just bothered me so much I could not let them go. I had to change them. I hope you enjoy the branch name :)
> fixed some grammar

- ui/chatview.go
- ui/chatview_test.go
I don't like clicking links senpai
> Custom emoji render

- app/app.go
- ui/login.go
Token validation is now performed by attempting to make the socket connection  like the official clients.
> Token validation is now performed by attempting to make a socket connection  #206

- shortcuts/dialog.go
- shortcuts/table.go
- ui/channeltree.go
- ui/chatview.go
- ui/editor.go
- ui/login.go
- ui/privatechats.go
- ui/window.go
Takes advantage of DEC VTxxx screen features.
(requires merging [this](https://github.com/Bios-Marcel/tview/pull/6/))
https://www.youtube.com/watch?v=tj2eQA2SNF8
> DEC VT dumb terminals support

- commands/commandimpls/user.go
On branch fix-typo
Changes to be committed:
modified:   user.go
> This typo bugged me. 

- shortcuts/shortcuts.go
The shortcut text for deleting a message is the toggle spoiler message
> Fix the message deletion shortcut

- config/os.go
> Fix config directory

- README.md
"[check the wiki at]" -> "check [the wiki]"
> Fix link to wiki for tokens
